import type { BasicDataProps, ReceivedVtuber, ReceivedMovie, ReceivedKaraoke } from "@/types/vtuber_content"

export const mockVtubers: ReceivedVtuber[] = [
  {
    VtuberId: 1,
    VtuberName: "妹望おいも",
    VtuberKana: "imomochi_oimo",
    IntroMovieUrl: "www.youtube.com/watch?v=AlHRqSsF--8&t=75",
    VtuberInputterId: "user-001",
    Count: 42,
    IsFav: false,
  },
  {
    VtuberId: 2,
    VtuberName: "花咲みこと",
    VtuberKana: "hanasaki_mikoto",
    IntroMovieUrl: "www.youtube.com/watch?v=7QStB569mto&t=290",
    VtuberInputterId: "user-002",
    Count: 28,
    IsFav: true,
  },
  {
    VtuberId: 3,
    VtuberName: "星野あかり",
    VtuberKana: "hoshino_akari",
    IntroMovieUrl: null,
    VtuberInputterId: "user-003",
    Count: 15,
    IsFav: false,
  },
]

export const mockMovies: ReceivedMovie[] = [
  {
    VtuberId: 1,
    VtuberName: "妹望おいも",
    VtuberKana: "imomochi_oimo",
    IntroMovieUrl: "www.youtube.com/watch?v=AlHRqSsF--8&t=75",
    VtuberInputterId: "user-001",
    MovieUrl: "www.youtube.com/watch?v=9ehwhQJ50gs",
    MovieTitle: "【歌枠】初カラオケ配信！リクエスト100曲チャレンジ",
    MovieInputterId: 1,
    Count: 120,
    IsFav: false,
  },
  {
    VtuberId: 1,
    VtuberName: "妹望おいも",
    VtuberKana: "imomochi_oimo",
    IntroMovieUrl: "www.youtube.com/watch?v=AlHRqSsF--8&t=75",
    VtuberInputterId: "user-001",
    MovieUrl: "www.youtube.com/watch?v=AAsRtnbDs-0",
    MovieTitle: "【歌枠】深夜のしっとり歌配信",
    MovieInputterId: 1,
    Count: 85,
    IsFav: true,
  },
  {
    VtuberId: 2,
    VtuberName: "花咲みこと",
    VtuberKana: "hanasaki_mikoto",
    IntroMovieUrl: null,
    VtuberInputterId: "user-002",
    MovieUrl: "www.youtube.com/watch?v=LnL8i4c8sfo",
    MovieTitle: "【歌枠】アニソン縛り歌配信",
    MovieInputterId: 2,
    Count: 60,
    IsFav: false,
  },
]

export const mockKaraokes: ReceivedKaraoke[] = [
  {
    VtuberId: 1,
    VtuberName: "妹望おいも",
    VtuberKana: "imomochi_oimo",
    IntroMovieUrl: null,
    VtuberInputterId: "user-001",
    MovieUrl: "www.youtube.com/watch?v=9ehwhQJ50gs",
    MovieTitle: "【歌枠】初カラオケ配信！リクエスト100曲チャレンジ",
    MovieInputterId: 1,
    KaraokeId: 1,
    SingStart: "00:05:30",
    SongName: "残酷な天使のテーゼ",
    KaraokeInputterId: 1,
    Count: 30,
    IsFav: false,
  },
  {
    VtuberId: 1,
    VtuberName: "妹望おいも",
    VtuberKana: "imomochi_oimo",
    IntroMovieUrl: null,
    VtuberInputterId: "user-001",
    MovieUrl: "www.youtube.com/watch?v=9ehwhQJ50gs",
    MovieTitle: "【歌枠】初カラオケ配信！リクエスト100曲チャレンジ",
    MovieInputterId: 1,
    KaraokeId: 2,
    SingStart: "00:15:20",
    SongName: "ハート型ウイルス",
    KaraokeInputterId: 1,
    Count: 18,
    IsFav: true,
  },
  {
    VtuberId: 2,
    VtuberName: "花咲みこと",
    VtuberKana: "hanasaki_mikoto",
    IntroMovieUrl: null,
    VtuberInputterId: "user-002",
    MovieUrl: "www.youtube.com/watch?v=LnL8i4c8sfo",
    MovieTitle: "【歌枠】アニソン縛り歌配信",
    MovieInputterId: 2,
    KaraokeId: 3,
    SingStart: "00:08:45",
    SongName: "紅蓮華",
    KaraokeInputterId: 2,
    Count: 45,
    IsFav: false,
  },
]

export const mockBasicData: BasicDataProps = {
  vtubers: mockVtubers,
  vtubers_movies: mockMovies,
  vtubers_movies_karaokes: mockKaraokes,
}
