name: API (Go)

on:
  push:
    branches: ["*"]
    paths:
      - 't0016Go/**'
      - 'docker-compose*.yml'
      - 'ec2-docker-compose.yml'
      - '.github/workflows/**'
  pull_request:
    branches: [develop]
    paths:
      - 't0016Go/**'
      - 'docker-compose*.yml'
      - 'ec2-docker-compose.yml'
      - '.github/workflows/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build
      run: go build -v ./...
      working-directory: t0016Go/.

    - name: Test
      run: go test -v ./...
      working-directory: t0016Go/.
